//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_operation.Models
{
    using System;
    using System.Collections.Generic;
    //add validation
    using System.ComponentModel.DataAnnotations;
    
    public partial class Railways_Details
    {
        [Required]
        
        public int pnrnumber { get; set; }
        [Required]
        [StringLength(20,ErrorMessage ="Name must be 20 length")]
        public string passname { get; set; }
        [Required]
        public Nullable<System.DateTime> dateoftravel { get; set; }
        [Required]
        public string source { get; set; }
        [Required]
        public string destination { get; set; }
        [Required]
        public Nullable<int> ticketprice { get; set; }
    }
}
